### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Catherinelhl** [BorderCloud/SPARQL-ANDROID#1]
Hi,I have a program with it:https://stackoverflow.com/questions/27366430/getting-nosuchfielderror-instance-org-apache-http-message-basicheadervalueparser.so ,I saw this tips about how to solve it.But i don't know how to use it.I paste your code to my editor and running it,but it doesn't work.I think i have's to use it with a right method.I need your help,thanx.

**Comment by ghost** [comment]
I have this question too.

**Comment by BorderCloud** [comment]
I updated this project.
